name: Test
on: 
  workflow_dispatch:
    inputs:
      case:
        type: choice
        description: Case
        options: 
        - 1
        - 2
        - 3
        - 4
        - 5

jobs:
  test1:
    runs-on: ubuntu-latest
    if: github.event.inputs.case == 'all' || github.event.inputs.case == 1
    steps:
      - uses: actions/checkout@v5
      - name: test case 1
        run: test/case1.sh
        env:
          GITHUB_TOKEN: ${{ secrets.TRIGGER_EVENTS_TOKEN }}

  test2:
    runs-on: ubuntu-latest
    if: github.event.inputs.case == 'all' || github.event.inputs.case == 2
    steps:
      - name: resync forked repo
        run: |
          gh repo sync \
          --force \
          --source korthout/backport-action-test \
          backport-action/backport-action-test
        env:
          GITHUB_TOKEN: ${{ secrets.BACKPORT_ACTION_TOKEN }}
      - uses: actions/checkout@v5
        with: 
          repository: backport-action/backport-action-test
          token: ${{ secrets.TRIGGER_EVENTS_TOKEN }}
      - name: test case 2
        run: test/case2.sh
        env:
          GITHUB_TOKEN: ${{ secrets.TRIGGER_EVENTS_TOKEN }}

  test3:
    runs-on: ubuntu-latest
    if: github.event.inputs.case == 'all' || github.event.inputs.case == 3
    steps:
      - uses: actions/checkout@v5
      - name: test case 3
        run: test/case3.sh
        env:
          GITHUB_TOKEN: ${{ secrets.TRIGGER_EVENTS_TOKEN }}
  
  test4:
    runs-on: ubuntu-latest
    if: github.event.inputs.case == 'all' || github.event.inputs.case == 4
    steps:
      - uses: actions/checkout@v5
      - name: test case 4
        run: test/case4.sh
        env:
          GITHUB_TOKEN: ${{ secrets.TRIGGER_EVENTS_TOKEN }}

  test5:
    runs-on: ubuntu-latest
    if: github.event.inputs.case == 'all' || github.event.inputs.case == 5
    steps:
      - uses: actions/checkout@v5
      - name: test case 5
        run: test/case5.sh
        env:
          GITHUB_TOKEN: ${{ secrets.TRIGGER_EVENTS_TOKEN }}
